name: macOS latest

on: [ push, pull_request ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Python:
    runs-on: macos-latest
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.10', 3.11]
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        uses: pypa/cibuildwheel@v2.12.3
        run: |
          brew install sdl2 sdl2_image sdl2_mixer sdl2_ttf pkg-config
          python -m pip install setuptools -U
          python -m pip install pygame-ce
          python -m pip install . --use-pep517
      - name: Run Tests
        run: |
          python -m unittest