name: Windows latest

on: [push, pull_request]

jobs:
  on_build_actions:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install package
        run: |
          python -m pip install --upgrade pip
          python -m pip install pygame
          pip install .
      - name: Run Tests    
        run: python -m unittest
